version: '3'
services:
  learnvault:
    container_name: learnvault
    build: .
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb/LearnVault
    ports:
      - '7777:7777'
    depends_on:
      - mongodb
    networks:
      - learnvault-network

  mongodb:
    container_name: learnvault-mongo
    image: mongo
    restart: always
    volumes:
      - './dbdata:/data/db'
    networks:
      - learnvault-network

volumes:
  dbdata:

networks:
  learnvault-network:
    driver: bridge

